name: Build Arch Linux image for Aarch64

# Workflow to build an Arch Linux image for Aarch64
on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9]'

  workflow_dispatch:

jobs:
  build:
    # runs-on: ubuntu-latest
    # We use self-hosted runner, because Github creates images that are twice as big as the ones created on self-hosted runner
    # ~ 300MB vs ~ 600MB
    runs-on: self-hosted
    name: Build Images
    permissions:
      contents: write

    strategy:
      matrix:
        model_name:
          - "generic-uefi"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          # Extract just the build number (e.g., "01") from a tag like "20250511-01"
          # ${GITHUB_REF_NAME} will be the tag name, e.g., 20250511-01
          # ${GITHUB_REF_NAME##*-} extracts just the 01 part.
          export BUILD_SUFFIX="${GITHUB_REF_NAME##*-}"
          bash <(curl -fsSL https://raw.githubusercontent.com/mschirrmeister/archlinux-lima/main/create-image.sh)
          cp -r /tmp/lima/output/Arch-Linux-aarch64-cloudimg-*.xz .

      - name: Upload to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Arch-Linux-aarch64-cloudimg-*.xz"
          makeLatest: true
          allowUpdates: true
          omitBody: true

      - name: Cleanup output directory
        run: |
          echo "Before cleanup:" && ls -lh /tmp/lima/output/
          rm -f /tmp/lima/output/*
          echo "After cleanup:" && ls -lh /tmp/lima/output/